helper_func.o: helper_func.cc ../../libs/essbt/helper_func.h \
 ../../libs/essbt/defines.h ../../libs/mve/mesh.h \
 ../../libs/math/vector.h ../../libs/math/defines.h \
 ../../libs/math/algo.h ../../libs/mve/defines.h ../../libs/mve/camera.h \
 ../../libs/mve/bundle.h ../../libs/math/matrix.h ../../libs/mve/scene.h \
 ../../libs/mve/view.h ../../libs/mve/image_base.h \
 ../../libs/util/strings.h ../../libs/util/defines.h \
 ../../libs/mve/image.h ../../libs/math/functions.h \
 ../../libs/mve/mesh_io.h
